# Import the standard time module to track call duration and timestamp metrics
import time
# Import Typing constructs for type hints and structural clarity
from typing import Any, Dict
# Import BaseClass/Field from Pydantic to structure output metadata schema
from pydantic import BaseModel, Field

# Define a structured container for LLM request/response execution metadata
class LLMMetadata(BaseModel):
    # Track the total execution time of the request in seconds
    latency_seconds: float = Field(
        ..., description="Total execution timein seconds"
    )
    # Track the count of tokens sent in the prompt payload
    prompt_tokens: int = Field(
        ..., description="Number of tokens in the input prompt"
    )
    # Track the count of tokens generated in the API completion payload
    completion_tokens: int = Field(
        ..., description="Number of tokens generated by the model"
    )
    # Track total token volume across input and output fields
    total_tokens: int = Field(
        ..., description="Sum of prompt and completion tokens"
    )
    # Calculate total financial cost accrued by the request
    total_cost_usd: float =Field(
        ..., description="Calculated request cost in USD"
    )

# Intercept cal execution to record start/end timestamps and parse metrics
def extract_metadata(
    response_payload: Dict[str, Any], start_time: float, end_time:float
) -> LLMMetadata:
    # Calculate elapsed execution time in seconds using timestamp parameters 
    latency = end_time - start_time

    # Extract token breakdown dictionary safely from the API response object
    usage = response_payload.get("usage", {})

    # Extract input token usage count from dictionary with default fallback
    p_tokens = usage.get("prompt_tokens", 0)

    # Extract output token usage count from dictionary with default fallback
    c_tokens = usage.get("completion_tokens", 0)

    # Calculate cost assuming $0.0015 per 1k prompt tokens and $0.002 per 1k completion tokens
    cost = (p_tokens / 1000 * 0.0015) + (c_tokens / 1000 * 0.002)

    # Instantiate and return the validated metadata schema object
    return LLMMetadata(
        latency_seconds=latency,
        prompt_tokens=p_tokens, 
        completion_tokens=c_tokens,
        total_tokens=p_tokens + c_tokens,
        total_cost_usd=cost,
    )