from unittest.mock import patch
from fastapi.testclient import TestClient

# Import the FastAPI instance, demo function, and schemas
from ai_sandbox.main import app, run_demo
from ai_sandbox.schemas import AIRequest

# Initialize TestClient with the FastAPI application instance
client = TestClient(app)

def test_health_check_endpoint():
    """Verify that the Get /health endpoint returns HTTP 200 and expected status."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}

def test_run_demo_instantiation(capsys):
    """Verify run_demo successfully instantiates AIRequest and prints stdout."""
    run_demo()

    # Capture stdout output generated by print statemetns in run_demo
    captured = capsys.readouterr()

    assert "Successfully instantiated model!" in captured.out
    assert "User Email: developer@example.com" in captured.out
    assert "Model Name: gpt-4o" in captured.out
    assert "Is Premium: True" in captured.out

def test_run_demo_creates_valid_schema():
    """Verify that run_demo creates a valid AIRequest instance directly."""
    # Execute run_demo and verify real Pydantic object creation
    with patch("ai_sandbox.main.AIRequest", wraps=AIRequest) as spy_airequest:
        run_demo()

    # Verify constructor was called with expected payload key-value pairs
    spy_airequest.assert_called_once_with(
        request_id="req-99999",
        user={
            "user_id": "usr_77",
            "email": "developer@example.com",
            "is_premium": True,
        },
        config={"temperature": 0.8, "model_name": "gpt-4o"},
        prompt="Explain Quantum Physics like I am five.",
    )